Repository theforeman/puppet-katello, pull requests merged in 2018-09, with the labels that each got.

#253 Fixes #24854 - Update rest_client param reference in application.pp
  manifests/application.pp
Labels: Needs testing, Not yet reviewed

#254 Fixes #24854 - Update rest_client param reference in application.pp
  manifests/application.pp
Labels: Bug, Needs testing

#255 Allow newest module dependencies
  metadata.json
Labels: Enhancement, Needs testing, Not yet reviewed
