Repository theforeman/puppet-katello, pull requests merged in 2020-01, with the labels that each got.

#305 Use the nss cert name from certs::qpid
  manifests/qpid.pp
  manifests/qpid_client.pp
  metadata.json
Labels: Needs testing

#313 Refs #28695: Add Pulp 2 migration settings
  manifests/application.pp
  manifests/init.pp
  spec/classes/application_spec.rb
  templates/katello.yaml.erb
Labels: Needs testing

#314 Compatibility with katello/certs 7.x
  manifests/pulp.pp
  metadata.json
  spec/classes/pulp_spec.rb
Labels: Needs testing

#317 Add needed fixtures
  .fixtures.yml
Labels: Needs testing, Not yet reviewed

#318 Fixes #28848: Deploy dynflow worker dedicated to hosts_queue
  manifests/application.pp
  spec/classes/application_spec.rb
Labels: Needs testing

#315 Fixes #28837 - removes cdn_proxy from config
  manifests/application.pp
  manifests/init.pp
  spec/classes/application_spec.rb
  templates/katello.yaml.erb
Labels: Backwards incompatible, Needs testing

#319 Fixes #28888 - add cert auth for docker registry
  templates/pulp-apache-ssl.conf.erb
Labels: Needs testing
