Repository theforeman/puppet-katello, pull requests merged in 2020-10, with the labels that each got.

#362 never deploy /pub, that's handled by f_p_c now
  manifests/pulp.pp
  templates/pulp-apache-ssl.conf.erb
  templates/pulp-apache.conf.erb
Labels: Backwards incompatible, Needs testing

#363 don't configure Pulp2 when running on EL8
  manifests/application.pp
  manifests/globals.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/application_spec.rb
  templates/katello.yaml.erb
Labels: Needs testing

#365 Do not enable Puppet if there is no Pulp 2
  manifests/application.pp
  spec/classes/application_spec.rb
Labels: Needs testing

#367 Switch to GH Actions from Travis
  .github/workflows/acceptance.yml
  .github/workflows/cron.yml
  .github/workflows/unit.yml
  .travis.yml
Labels: Modulesync, Needs testing, skip-changelog

#366 Require puppet-candlepin 11.0.0+
  metadata.json
Labels: Needs testing, skip-changelog

#368 Release 16.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
