Repository theforeman/puppet-katello, pull requests merged in 2020-06, with the labels that each got.

#341 Add postgresql-debversion extension to katello
  manifests/application.pp
  manifests/globals.pp
  manifests/params.pp
  spec/classes/application_spec.rb
Labels: Needs testing, Waiting on contributor

#339 Add Candlepin acceptance tests
  .travis.yml
  spec/acceptance/candlepin_spec.rb
  spec/setup_acceptance_node.pp
Labels: Needs testing

#347 Fixes #30023: Add Katello config for Pulp 3 RPM
  manifests/application.pp
  manifests/init.pp
  spec/classes/application_spec.rb
  templates/katello.yaml.erb
Labels: Needs testing

#349 Refs #30023 - Enable katello_applicability based on yum support
  spec/classes/application_spec.rb
  templates/katello.yaml.erb
Labels: Enhancement, Needs testing

#352 Remove non-working providers and types
  lib/puppet/provider/katello_activation_key/katello_cli.rb
  lib/puppet/provider/katello_cli.rb
  lib/puppet/provider/katello_repo/katello_cli.rb
  lib/puppet/type/katello_activation_key.rb
  lib/puppet/type/katello_common.rb
  lib/puppet/type/katello_repo.rb
Labels: Needs testing

#353 Revert "Add postgresql-debversion extension to katello"
  manifests/application.pp
  manifests/globals.pp
  manifests/params.pp
  spec/classes/application_spec.rb
Labels: Needs testing, skip-changelog

#354 Release 14.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
