Repository theforeman/puppet-katello, pull requests merged in 2020-05, with the labels that each got.

#337 Support manage_httpd to allow Pulp in a standalone setup (followup)
  manifests/pulp.pp
  spec/classes/pulp_spec.rb
Labels: Needs testing

#338 Modulesync: Require voxpupuli-test 1.4
  Gemfile
  Rakefile
  spec/spec_helper_acceptance.rb
Labels: Needs testing, Not yet reviewed

#335 Refs #29215: Only install Pulp and Qpid on EL7
  manifests/application.pp
  manifests/init.pp
  metadata.json
  spec/classes/application_spec.rb
  spec/classes/init_spec.rb
  spec/classes/pulp_spec.rb
  spec/classes/qpid_client_spec.rb
  spec/classes/qpid_spec.rb
Labels: Needs testing, Not yet reviewed

#336 Refs #28924: Drop qpid client configuration used by older katello-qpid
  manifests/application.pp
  manifests/qpid_client.pp
  spec/classes/application_spec.rb
  spec/classes/init_spec.rb
  spec/classes/qpid_client_spec.rb
Labels: Needs testing

#343 Update module dependencies to allow EL8 supported versions
  metadata.json
Labels: Needs testing, Not yet reviewed

#345 correct needed foreman dependency
  metadata.json
Labels: Needs testing

#344 Release 14.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs re-review, Needs testing, skip-changelog
