Repository theforeman/puppet-katello, pull requests merged in 2021-05, with the labels that each got.

#412 Allow Puppet 7 compatible versions of mods
  metadata.json
Labels: Needs testing, Not yet reviewed

#403 Clean up some of our tests
  spec/classes/application_spec.rb
Labels: Needs testing

#414 Switch to voxpupuli-acceptance-1.0
  Gemfile
  spec/acceptance/candlepin_spec.rb
  spec/acceptance/qpid_spec.rb
  spec/spec_helper_acceptance.rb
Labels: Needs testing, skip-changelog
