Repository theforeman/puppet-katello, pull requests merged in 2021-02, with the labels that each got.

#378 Release 17.0.0
  CHANGELOG.md
Labels: Needs testing

#379 Fixes #31761 - create katello.agent qpid queue
  manifests/application.pp
  manifests/params.pp
  manifests/qpid.pp
  spec/classes/application_spec.rb
  spec/classes/qpid_spec.rb
  templates/katello.yaml.erb
  templates/qpid_acls.acl
Labels: Needs testing

#380 Fixes #30360: Remove Pulp 2 deployment code
  manifests/application.pp
  manifests/globals.pp
  manifests/init.pp
  manifests/params.pp
  manifests/pulp.pp
  spec/classes/application_spec.rb
  spec/classes/init_spec.rb
  spec/classes/pulp_spec.rb
  templates/katello.yaml.erb
Labels: Needs testing

#381 Refs #30360: Remove unused dependencies
  .fixtures.yml
  metadata.json
Labels: Needs testing

#382 Release 18.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#383 No need to configure qpid::client
  manifests/application.pp
  manifests/qpid_client.pp
  spec/classes/application_spec.rb
  spec/classes/init_spec.rb
  spec/classes/qpid_client_spec.rb
  spec/classes/qpid_spec.rb
Labels: Needs testing

#385 Refs #31880 - Switch to AMQP 1.0 SSL URL
  manifests/params.pp
  spec/classes/application_spec.rb
Labels: Enhancement, Needs testing, Waiting on contributor

#384 Fixes #31878: Turn on Qpid auth and set ACLs to the router certificat…
  manifests/qpid.pp
  templates/qpid_acls.acl
Labels: Backwards incompatible, Enhancement

#386 Require puppet-certs 11+
  metadata.json
Labels: Needs testing
