Repository theforeman/puppet-katello, pull requests merged in 2021-04, with the labels that each got.

#364 Refs #29817 - Implement a resizable hosts_queue pool
  manifests/application.pp
  manifests/init.pp
  metadata.json
  spec/classes/application_spec.rb
Labels: Needs testing

#399 Remove Scientific 8 support from metadata.json
  metadata.json
Labels: Needs testing

#396 Update yumrepo to use yum.theforeman.org
  manifests/repo.pp
  spec/classes/repo_spec.rb
Labels: Needs testing

#398 Update Limitations in README
  README.md
Labels: Needs testing

#400 Allow puppet-qpid 8+
  metadata.json
Labels: Needs testing

#402 Refs #32369 - Move content enable flags to params
  manifests/globals.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/application_spec.rb
  types/hieraboolean.pp
Labels: Needs testing

#387 Refs #32037: Add flag to enable katello_agent infrastructure and disable it by default
  manifests/application.pp
  manifests/globals.pp
  manifests/params.pp
  manifests/qpid.pp
  metadata.json
  spec/acceptance/qpid_spec.rb
  spec/classes/application_spec.rb
  spec/classes/qpid_spec.rb
  templates/katello.yaml.erb
Labels: Needs testing

#401 Fixes #32160 - enable ansible collection content
  manifests/application.pp
  manifests/globals.pp
  manifests/params.pp
  spec/classes/application_spec.rb
  templates/katello.yaml.erb
Labels: Enhancement, Needs testing

#408 Allow puppet-certs < 13.0.0
  metadata.json
Labels: Enhancement, Needs testing

#407 Release 20.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog

#410 Remove unused Pulp Apache templates
  templates/pulp-apache-ssl.conf.erb
  templates/pulp-apache.conf.erb
Labels: Needs testing
