Repository theforeman/puppet-katello, pull requests merged in 2021-06, with the labels that each got.

#392 Support Puppet 7
  .github/workflows/ci.yml
  metadata.json
Labels: Enhancement, Needs testing

#417 Allow puppet-candlepin 12.0.0
  metadata.json
Labels: Needs testing

#418 Bump version to 21.0.0
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog

#416 Drop Puppet 5 support
  metadata.json
Labels: Backwards incompatible, Needs testing

#415 Allow certs 14.0.0
  metadata.json
Labels: Needs testing

#421 Allow puppet-qpid 9.0.0
  metadata.json
Labels: Enhancement, Needs testing

#422 Allow puppet-foreman 18.0.0
  metadata.json
Labels: Enhancement, Needs re-review, Needs testing
