Repository theforeman/puppet-katello, pull requests merged in 2023-11, with the labels that each got.

#482 Mark compatible with puppetlabs/stdlib 9.x
  metadata.json
Labels: Not yet reviewed, Enhancement

#483 Mark compatible with puppet-extlib 7.x
  metadata.json
Labels: Not yet reviewed, Enhancement

#484 Mark compatible with Puppet 8
  metadata.json
Labels: Enhancement

#485 Mark compatible with katello/qpid 11.x
  metadata.json
Labels: Enhancement

#480 Remove traces of EL7 from testing purge_katello
  spec/support/acceptance/purge.rb
Labels: skip-changelog

#487 Remove invalid default for $katello::repo::repo_version
  manifests/repo.pp
  spec/classes/application_spec.rb
  spec/classes/repo_spec.rb
Labels: Bug

#486 Release 24.2.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
